name: "CI"

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  build:
    name: "Build / ${{ matrix.os}}"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: "${{ matrix.os }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Setup Haskell
        uses: haskell-actions/setup@v2

      - name: Build
        run: cabal build
